### ISSUE TITLE
Cannot add claims to user.  An item with the same key has already been added.

### ISSUE THREAD

**Issue by spelltwister** [dlmelendez/identityazuretable#38]
Hello -

I've been using your libraries for a while now going back to asp.net 4 and am so thankful that you created this project :) 👍 

I updated my website to Asp.net core 2.1 using razor pages.  Originally, I was targeting netcoreapp2.1 and everything was working great.  I could create users and add claims to them no problem.  Authorization Policies were able to see the claims and all was well.  Then I had an issue with another package which required me to retarget to full framework 4.7.1 (net471).  After doing this, I started getting this exception when trying to add claims to my users.

```
Microsoft.WindowsAzure.Storage.StorageException
  HResult=0x80131500
  Message=An item with the same key has already been added.
  Source=Microsoft.WindowsAzure.Storage
  StackTrace:
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndExecuteBatch(IAsyncResult asyncResult)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ElCamino.AspNetCore.Identity.AzureTable.Helpers.BatchOperationHelper.<>c__DisplayClass4_1.<<ExecuteBatchAsync>b__1>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Inner Exception 1:
ArgumentException: An item with the same key has already been added.
```
This code works when targeting netcoreapp2.1 and does not work when targeting net471.
```
var result = await _userManager.CreateAsync(user, Input.Password);
if (result.Succeeded)
{
    _logger.LogInformation("User created a new account with password.");
    
    if (user.UserName.EndsWith("@mycompany.com", StringComparison.OrdinalIgnoreCase))
    {
        await this._userManager.AddClaimAsync(user, new System.Security.Claims.Claim("Access", "Administrator"));
    }
```
I tried using `WindowsAzure.Storage Version="9.3.0"` and `WindowsAzure.Storage Version="8.6.0"` with same result.

To retarget, replace `Microsoft.AspNetCore.App` package with the following:
```
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.CookiePolicy" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" PrivateAssets="All" />
    <PackageReference Include="ElCamino.AspNetCore.Identity.AzureTable" Version="2.1.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.0" />
```

and update the property group with

```
    <TargetFramework>net471</TargetFramework>
    <DebugType>Full</DebugType>
```

**Comment by dlmelendez** [comment]
@spelltwister Unfortunately, this issue has come up before with the WindowsAzure.Storage library. Check out #12 . It is frustrating that this bug keeps showing up but this is an issue with the storage library. The Windows.Storage library is officially deprecated on taking changes as the MS Cosmos DB team is going to take over the library. Not sure where this bug will land on their priority scale.

**Comment by dlmelendez** [comment]
@spelltwister While this is a bug in the underlying storage library, I just found a workaround. Removing the Id property override seems to fix the problem. I will get this fix put into next release.

**Comment by dlmelendez** [comment]
v2.2.1 fixed.
