### ISSUE TITLE
CreateAzureTablesIfNotExists throws when TUser is not public, does not wait for completion

### ISSUE THREAD

**Issue by davidnx** [dlmelendez/identityazuretable#74]
The extension method `IdentityBuilder.CreateAzureTablesIfNotExists` has a nasty use of `dynamic` to invoke `UserStore.CreateTablesIfNotExistsAsync`. Not only does this prevent type safety checks the compiler could help with, it also causes runtime issues that pose a terribe debugging experience when using an internal `TUser` instantiation.

Problematic code:
https://github.com/dlmelendez/identityazuretable/blob/62f63b216dc1b67c91e4fe45886d0bb32287e2c1/src/ElCamino.AspNetCore.Identity.AzureTable/IdentityAzureTableBuilderExtensions.cs#L63-L66

The method above is also not waiting for the task to complete, and if it were to fail, could lead to UnobservedTaskExceptions that could cause the entire process to fail.

### Repro code:

In Startup.cs of a project, inside `ConfigureServices`:

```cs
services.AddIdentity<MyUser, MyRole>()
    .AddAzureTableStores<MyContext>(() => new IdentityConfiguration { /* ... */ });
    .AddDefaultTokenProviders()
    .CreateAzureTablesIfNotExists<MyContext>(); // Throws when MyUser is declared as internal
```

Exception:
```
Exception in ConfigureServices: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'object' does not contain a definition for 'CreateTablesIfNotExistsAsync'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at Microsoft.Extensions.DependencyInjection.IdentityAzureTableBuilderExtensions.CreateAzureTablesIfNotExists[TContext](IdentityBuilder builder)
   at DemoApp.Startup.ConfigureServices(IServiceCollection services)
```

**Comment by davidnx** [comment]
Suggested fix without large refactoring: Add an internal interface `ICreateTablesIfNotExistsAsync` that `UserStore` will implement. Now `IdentityAzureTableBuilderExtensions.CreateAzureTablesIfNotExists` can explicitly cast the object it got to this new interface, and invoke `CreateTablesIfNotExistsAsync` on it. This doesn't achieve compile-time type safety, but mitigates the other concerns.
