### ISSUE TITLE
UserManager.GetUsersInRoleAsync throws exception after upgrade from 2.2.1 to 5.1

### ISSUE THREAD

**Issue by brianrak** [dlmelendez/identityazuretable#84]
After upgrading Identity.AzureTable from 2.2.1 to 5.1 and running against an existing user database, I started getting exceptions when calling UserManager.GetUsersInRoleAsync. The exception is:

```
Object of type 'System.DateTimeOffset' cannot be converted to type 'System.Nullable`1[System.DateTime]'.
```

**When I move back to Identity.AzureTable 5.0, the error goes away.**

Also, I was unsure if I needed to run data migration on my database, so I created a replica of the database, set up a copy of my site running 5.1, and verified I could repro the issue. Then I ran data migration on the replica and ran my site against the migrated tables. **The exception continued to occur** in the same place, so it appears to be unrelated to data migration.

However, the exception does seem to be related somehow to my data. I have other test databases, and when I run 5.1 against them, I don't get the exception. It only occurs against my production data. I can't think of any structural difference between my test data and my production data. I could try to provide you a cleaned subset of the data if that would be useful. My database has about 90K users. I'm not sure how I can easily take a slice of that such that all the related pieces come as a set, but I would be happy to work with you to do so.

Here is the stack trace for the exception:

```
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at ElCamino.AspNetCore.Identity.AzureTable.UserOnlyStore`6.MapTableEntity[T](TableEntity dte)
   at ElCamino.AspNetCore.Identity.AzureTable.UserStore`8.MapUserAggregate(String userId, IEnumerable`1 userResults, Func`2 whereRole, Func`2 whereClaim)
   at ElCamino.AspNetCore.Identity.AzureTable.UserStore`8.<>c__DisplayClass10_0.<GetUserAggregateQueryAsync>b__1(Task`1 taskResults)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ElCamino.AspNetCore.Identity.AzureTable.UserStore`8.<GetUserAggregateQueryAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ElCamino.AspNetCore.Identity.AzureTable.UserOnlyStore`6.<>c__DisplayClass42_0.<<GetUsersAggregateByIndexQueryAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at ElCamino.AspNetCore.Identity.AzureTable.UserOnlyStore`6.<GetUsersAggregateByIndexQueryAsync>d__42.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ElCamino.AspNetCore.Identity.AzureTable.UserStore`8.<GetUsersInRoleAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at [REDACTED] in C:\Users\[REDACTED]
```

**Comment by dlmelendez** [comment]
Unable to repro. Try v6.0 when it is released and see if you have the same issue. It is possible the ignored members in the models are causing serialization issues. The members are ignored again in the serialization in 6.0.

**Comment by dlmelendez** [comment]
Closing for lack of feedback on v6.0 and unable to reproduce.
